version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana_container
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring_network
    volumes:
      - grafana-volume:/var/lib/grafana
  influxdb:
    image: influxdb
    container_name: influxdb_container
    restart: always
    ports:
      - 8086:8086
      - 8089:8089/udp
    networks:
      - monitoring_network
    volumes:
      - influxdb-volume:/var/lib/influxdb
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter_container
    ports:
      - 9100:9100
    restart: always
    networks:
      - monitoring_network
    volumes:
      - node_exporter-volume:/host:ro,rslave
  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    ports:
      - 9090:9090
    restart: always
    networks:
      - monitoring_network
    volumes:
      - /root/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-volume:/prometheus

networks:
  monitoring_network:
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
  node_exporter-volume:
    external: true
  prometheus-volume:
    external: true
